"""Markdown report exporter and formatter."""

from pathlib import Path
from genar.models.report import ReportDocument


def export_markdown_report(report_doc: ReportDocument, output_path: str | Path) -> Path:
    """Serialize ReportDocument to a clean, professionally formatted Markdown file."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    meta = report_doc.metadata
    lines = [
        f"# {meta.report_type}: Periodic Adverse Drug Experience Report",
        "",
        f"**Product Name:** {meta.product_name}",
        f"**Manufacturer:** {meta.manufacturer}",
        f"**Reporting Period:** {meta.reporting_period_start} to {meta.reporting_period_end}",
        f"**Report ID:** `{meta.report_id}`",
        f"**Generated At:** {meta.generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}",
        f"**Approval Status:** {'[APPROVED]' if meta.is_fully_approved else '[PENDING REVIEW]'}",
        "",
        "---",
        "",
    ]

    # Append all section drafts
    for section in report_doc.sections:
        lines.append(section.markdown_content)
        lines.append("")
        lines.append("---")
        lines.append("")

    # Regulatory signature block
    lines.extend([
        "## Review & Verification Sign-Off",
        "",
        "| Section ID | Status | Reviewer | Timestamp |",
        "| :--- | :--- | :--- | :--- |",
    ])
    for rev in report_doc.review_records:
        ts_str = rev.reviewed_at.strftime('%Y-%m-%d %H:%M:%S UTC') if rev.reviewed_at else "N/A"
        lines.append(f"| {rev.section_id} | {rev.status.value} | {rev.reviewer_name or 'Pending'} | {ts_str} |")

    lines.append("")
    lines.append("*Report generated by GenAR Automated Pharmacovigilance Regulatory Engine (FDA 21 CFR 314.80).*")

    content = "\n".join(lines)
    path.write_text(content, encoding="utf-8")
    return path
